// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBraRq_VTs87_0Xq8lvLVf_43JDGnqTCQE',
    appId: '1:269291418812:web:a62cce47dd019cc85fccb9',
    messagingSenderId: '269291418812',
    projectId: 'lanka-explorer-c0398',
    authDomain: 'lanka-explorer-c0398.firebaseapp.com',
    storageBucket: 'lanka-explorer-c0398.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6onVnEAysWMbapc-gUQ6ZEuLJBETQSqM',
    appId: '1:269291418812:android:cd75ff8ca4d26e495fccb9',
    messagingSenderId: '269291418812',
    projectId: 'lanka-explorer-c0398',
    storageBucket: 'lanka-explorer-c0398.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpOWBfn1aJcxkpWLwdv__8ufzx32s9DWw',
    appId: '1:269291418812:ios:42819b010e0f2c8a5fccb9',
    messagingSenderId: '269291418812',
    projectId: 'lanka-explorer-c0398',
    storageBucket: 'lanka-explorer-c0398.firebasestorage.app',
    iosBundleId: 'com.example.lankaExplorer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpOWBfn1aJcxkpWLwdv__8ufzx32s9DWw',
    appId: '1:269291418812:ios:42819b010e0f2c8a5fccb9',
    messagingSenderId: '269291418812',
    projectId: 'lanka-explorer-c0398',
    storageBucket: 'lanka-explorer-c0398.firebasestorage.app',
    iosBundleId: 'com.example.lankaExplorer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBraRq_VTs87_0Xq8lvLVf_43JDGnqTCQE',
    appId: '1:269291418812:web:1e9bf69f2b549b025fccb9',
    messagingSenderId: '269291418812',
    projectId: 'lanka-explorer-c0398',
    authDomain: 'lanka-explorer-c0398.firebaseapp.com',
    storageBucket: 'lanka-explorer-c0398.firebasestorage.app',
  );

}